const FieldDummy = [
  {
    id: 24,
    ground_id: 24,
    source: '플랩풋볼',
    message: '존재하지 않는 구장 정보입니다.',
    title: '서울 노원 R 실내 풋살장',
    address: {
      area: '경기 / 의정부시',
      fullAddress: '경기 의정부시 산단로76번길 116',
    },
    stadiums: [
      {
        id: 81,
        name: null,
        size_x: 31,
        size_y: 15,
        is_rental: true,
        inout_door: 'OUTDOOR',
        inout_door_nm: '실외',
        stadium_type: 'ARTIGRASS',
        stadium_type_nm: '인조잔디',
        images: [Array],
        info: '15x31m, 인조잔디, 실외',
      },
    ],
    lat: 127.027500354604,
    lng: 37.6613189795285,
    is_parking: true,
    is_parking_free: true,
    is_shower: false,
    is_shoes: true,
    is_wear: false,
    is_ball: true,
    is_toilet: null,
    url: 'https://www.plabfootball.com/api/v2/stadium-groups/5',
  },
  {
    id: 24,
    ground_id: 24,
    source: '플랩풋볼',
    message: '존재하지 않는 구장 정보입니다.',
    title: '김포 손승준 축구클럽 풋살장',
    address: {
      area: '경기 / 의정부시',
      fullAddress: '경기 의정부시 산단로76번길 116',
    },
    stadiums: [
      {
        id: 81,
        name: null,
        size_x: 31,
        size_y: 15,
        is_rental: true,
        inout_door: 'OUTDOOR',
        inout_door_nm: '실외',
        stadium_type: 'ARTIGRASS',
        stadium_type_nm: '인조잔디',
        images: [Array],
        info: '15x31m, 인조잔디, 실외',
      },
    ],
    lat: 126.97022891847539,
    lng: 37.400793530244854,
    is_parking: true,
    is_parking_free: true,
    is_shower: false,
    is_shoes: true,
    is_wear: false,
    is_ball: true,
    is_toilet: null,
    url: 'https://www.plabfootball.com/api/v2/stadium-groups/5',
  },
  {
    id: 24,
    ground_id: 24,
    source: '플랩풋볼',
    message: '존재하지 않는 구장 정보입니다.',
    title: '대구 상인 풋살장 (롯데백화점 상인점)',
    address: {
      area: '경기 / 의정부시',
      fullAddress: '경기 의정부시 산단로76번길 116',
    },
    stadiums: [
      {
        id: 81,
        name: null,
        size_x: 31,
        size_y: 15,
        is_rental: true,
        inout_door: 'OUTDOOR',
        inout_door_nm: '실외',
        stadium_type: 'ARTIGRASS',
        stadium_type_nm: '인조잔디',
        images: [Array],
        info: '15x31m, 인조잔디, 실외',
      },
    ],
    lat: 126.9896748311281,
    lng: 37.41842077731433,
    is_parking: true,
    is_parking_free: true,
    is_shower: false,
    is_shoes: true,
    is_wear: false,
    is_ball: true,
    is_toilet: null,
    url: 'https://www.plabfootball.com/api/v2/stadium-groups/5',
  },
  {
    id: 24,
    ground_id: 24,
    source: '플랩풋볼',
    message: '존재하지 않는 구장 정보입니다.',
    title: '대구 에프에이필드 율하점',
    address: {
      area: '경기 / 의정부시',
      fullAddress: '경기 의정부시 산단로76번길 116',
    },
    stadiums: [
      {
        id: 81,
        name: null,
        size_x: 31,
        size_y: 15,
        is_rental: true,
        inout_door: 'OUTDOOR',
        inout_door_nm: '실외',
        stadium_type: 'ARTIGRASS',
        stadium_type_nm: '인조잔디',
        images: [Array],
        info: '15x31m, 인조잔디, 실외',
      },
    ],
    lat: 127.04711246030963,
    lng: 37.49892630571805,
    is_parking: true,
    is_parking_free: true,
    is_shower: false,
    is_shoes: true,
    is_wear: false,
    is_ball: true,
    is_toilet: null,
    url: 'https://www.plabfootball.com/api/v2/stadium-groups/5',
  },
  {
    id: 24,
    ground_id: 24,
    source: '플랩풋볼',
    message: '존재하지 않는 구장 정보입니다.',
    title: '의정부 김병지FC 풋살파크',
    address: {
      area: '경기 / 의정부시',
      fullAddress: '경기 의정부시 산단로76번길 116',
    },
    stadiums: [
      {
        id: 81,
        name: null,
        size_x: 31,
        size_y: 15,
        is_rental: true,
        inout_door: 'OUTDOOR',
        inout_door_nm: '실외',
        stadium_type: 'ARTIGRASS',
        stadium_type_nm: '인조잔디',
        images: [Array],
        info: '15x31m, 인조잔디, 실외',
      },
    ],
    lat: 127.13752931010741,
    lng: 37.46973507191079,
    is_parking: true,
    is_parking_free: true,
    is_shower: false,
    is_shoes: true,
    is_wear: false,
    is_ball: true,
    is_toilet: null,
    url: 'https://www.plabfootball.com/api/v2/stadium-groups/5',
  },
];

export default FieldDummy;
